# fly.toml file generated for dicensapi on 2022-08-06T22:22:21+03:00

app = "dicensapi"

[deploy]
  strategy = "bluegreen"

[env]
  ENV = "release"
  LOG_JSON_OUTPUT = true
  LOG_LEVEL = "info"
  PORT = 8081

[[services]]
  internal_port = 8085

  [[services.http_checks]]
    grace_period = "5s"
    interval = 10000
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.ports]]
    handlers = ["http"]
    port = "8081"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
