# fly.toml file generated for dicensapi on 2022-08-13T10:54:27+03:00

app = "dicensapi"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ENV = "release"
  LOG_JSON_OUTPUT = "t"
  LOG_LEVEL = "info"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  tcp_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    headers = []
    interval = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false

  [[services.ports]]
    handlers = ["http"]
    port = 8080

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
