name: Deploy

on:
  workflow_run:
    workflows:
      - "Build"
    branches:
      - 'main'
    types:
      - completed

jobs:

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      # https://github.com/superfly/flyctl-actions
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl secrets set ENV=${{ secrets.ENV }}
          flyctl secrets set LOG_LEVEL=${{ secrets.LOG_LEVEL }}
          flyctl secrets set PORT=${{ secrets.PORT }}
          flyctl secrets set DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          flyctl secrets set DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          flyctl secrets set DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
          flyctl secrets set DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD}}
          flyctl secrets set DATABASE_PORT=${{ secrets.DATABASE_PORT }}
          flyctl secrets set USERNAME=${{ secrets.USERNAME }}
          flyctl secrets set PASSWORD=${{ secrets.PASSWORD }}
          flyctl secrets set SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          flyctl secrets set SENTRY_ENV=${{ secrets.SENTRY_ENV }}
          flyctl secrets set SENTRY_SAMPLE_RATE=${{ secrets.SENTRY_SAMPLE_RATE }}
          flyctl secrets set SENTRY_ENABLED=${{ secrets.SENTRY_ENABLED }}
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
