name: Tests

on:
  workflow_run:
    workflows:
      - "Lint"
    types:
      - completed
  pull_request:
  push:

jobs:
  unittests:
    name: Unit Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run tests
        run: make test-coverage

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v2